import Head from 'next/head';
import * as S from '@/styles/styled';
import BaseLayout from '@/components/Layout/BaseLayout';
import React from 'react';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout hasHeader>
        <S.MainContent>
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((item) => {
            return (
              <S.MainContentItem
                layout
                key={item}
                initial={{
                  y: 10,
                  opacity: 0,
                }}
                animate={{
                  y: 0,
                  opacity: 1,
                }}
                whileHover={{
                  y: -3,
                }}
              >
                <div className="thumbnail">
                  <Link href={{ pathname: `/post`, query: { id: item } }} />
                </div>
                <div className="content">
                  <Link href={{ pathname: `/post`, query: { id: item } }}>
                    <div className="title">제목</div>
                    <div className="description">설명</div>
                  </Link>
                </div>
              </S.MainContentItem>
            );
          })}
        </S.MainContent>
      </BaseLayout>
    </>
  );
}
