import Head from 'next/head';
import * as S from '@/styles/styled';
import { MainContentDummy } from '@/styles/styled';
import Layout from '@/components/Layout';
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <S.MainContent>
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map((item) => {
            if (item > 10) {
              return <MainContentDummy key={item} />;
            }
            return (
              <S.MainContentItem
                layout
                key={item}
                initial={{
                  boxShadow: '0 0 1.3rem rgba(0, 0, 0, 0.2)',
                }}
                whileHover={{
                  y: -5,
                  boxShadow: '0 1rem 1.3rem rgba(0, 0, 0, 0.2)',
                }}
              >
                <div className="thumbnail"></div>
                <div className="content">
                  <div className="title">제목</div>
                  <div className="description">설명</div>
                </div>
              </S.MainContentItem>
            );
          })}
        </S.MainContent>
      </Layout>
    </>
  );
}
